
services:
  payload1:
    build: .
    restart: unless-stopped
    working_dir: /home/node/app
    ports:
      - '3010:3000'
    volumes:
      - media:/home/node/app/media   # persist uploads only
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - default

  # Ensure your DATABASE_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongodb:
    image: mongo:latest
    ports:
      - '27018:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

  # Uncomment the following to use postgres
  # postgres:
  #   restart: always
  #   image: postgres:latest
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  data:
  media:

  # pgdata:
  node_modules:
